### ISSUE TITLE
Multiple Rtsp streaming

### ISSUE THREAD

**Issue by linng85** [daniulive/SmarterStreaming#28]
Hi, do you support display multiple rtsp stream? I want the record function as well. I saw that you are charging for that. May i know how much you charge for the SmarterStreaming SDK? I don't have QQ by the way. Any other way to contact you?

Thanks.

**Comment by daniulive** [comment]
Hi,

Yes, we support multi-instance for rtmp/rtsp stream in windows/android/iOS.
You could refer to my email address with 89030985@qq.com.

For commercial support, we need to pay for license fees.

Thanks.

**Comment by linng85** [comment]
I emailed you yesterday. Haven't get any reply yet.

Thanks.

**Comment by daniulive** [comment]
Hi,

Sorry for late reply, since QQ email is regarded as junk mail automatically yesterday.

So which platform your company need to license? windows? android or iOS?

As for recording feature in multi-stream, you mean you want to record the prefered stream? for example, we playback 4 streams at the same time, and want to record the selected 1 stream?

We could communicate via email.

Thanks
Daniulive
